---
description: Pipeline for parsing Box Events
processors:
  - set:
      field: ecs.version
      value: "8.0.0"
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
