---
description: Pipeline for parsing Box Events
processors:
  - set:
      field: ecs.version
      value: "8.3.0"
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
  - json:
      field: event.original
      target_field: box
  - date:
      field: box.created_at
      target_field: "@timestamp"
      ignore_failure: true
      formats:
        - yyyy-MM-dd'T'HH:mm:ss-Z
  - rename:
      field: box.type
      target_field: event.kind
      ignore_missing: true
  - rename:
      field: box.created_by.type
      target_field: event.type
      ignore_missing: true
  - rename:
      field: box.event_type
      target_field: event.action
      ignore_missing: true
  - convert:
      field: box.source.sequence_id
      target_field: event.sequence
      type: integer
      ignore_missing: true
  - rename:
      field: box.source.type
      target_field: file.type
      ignore_missing: true
  - rename:
      if: ctx?.file?.type != "folder"
      field: box.source.name
      target_field: file.name
      ignore_missing: true
  - rename:
      if: ctx?.file?.type == "folder"
      field: box.source.name
      target_field: file.directory
      ignore_missing: true
  - rename:
      field: box.source.created_at
      target_field: file.created
      ignore_missing: true
  - rename:
      field: box.source.modified_at
      target_field: file.mtime
      ignore_missing: true
  - rename:
      field: box.source.size
      target_field: file.size
      ignore_missing: true
  - rename:
      field: box.source.file_version.sha1
      target_field: file.hash.sha1
      ignore_missing: true
  - remove:
      field: box.created_at
      ignore_missing: true
  - script:
      description: Drops null/empty values recursively
      lang: painless
      source: |
        boolean dropEmptyFields(Object object) {
          if (object == null || object == "") {
            return true;
          } else if (object instanceof Map) {
            ((Map) object).values().removeIf(value -> dropEmptyFields(value));
            return (((Map) object).size() == 0);
          } else if (object instanceof List) {
            ((List) object).removeIf(value -> dropEmptyFields(value));
            return (((List) object).length == 0);
          }
          return false;
        }
        dropEmptyFields(ctx);
on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
