input: httpjson
service: box_events
data_stream:
  vars:
    data_stream.dataset: box_events.events
    request_url: http://{{Hostname}}:{{Port}}/testtransforms/2.0/events?stream_position=123456789
    request_method: GET
    request_body: |-
      message:
        stream_position: 123456789
    request_transforms: |-
      - set:
          target: body.message.stream_position
          value: 123456789
    response_transforms: |-
      - set:
          target: body.test
          value: success
