input: httpjson
service: box_events
data_stream:
  vars:
    data_stream.dataset: box_events.events
    oauth_id: test
    oauth_secret: test
    oauth_subject_id: "test"
    oauth_token_url: http://{{Hostname}}:{{Port}}/testoauth/oauth2/token
    request_url: http://{{Hostname}}:{{Port}}/testoauth/2.0/events
